---
name: Read Vault Secrets
description: "... it reads secrets from Vault?"
inputs:
  address:
    description: "the address of a deployed vault server"
    required: false
    default: https://vault.rancher.engineering
  secrets:
    description: "the secrets to fetch from the vault server"
    required: false
    default: secret/data/github-actions/test status
outputs:
  secrets:
    description: "the secrets fetched from the vault server"
    value: ${{ steps.output.outputs.secrets }}
runs:
  using: composite
  steps:
    - name: Read Secrets from Vault
      uses: rancher-eio/vault-action@main
      id: vault
      with:
        method: jwt
        url: ${{ inputs.address }}
        path: ${{ github.repository_owner }}
        role: ${{ github.event.repository.name }}
        secrets: ${{ inputs.secrets }}
        exportEnv: false
        exportToken: false
        outputToken: false
        maskSecrets: false
    - name: Configure Outputs
      uses: actions/github-script@v7
      id: output
      with:
        script: |
          core.setOutput("secrets", ${{ toJSON(steps.vault.outputs) }});
          for (const [key, value] of Object.entries(${{ toJSON(steps.vault.outputs) }})) {
            core.setOutput(key, value);
          }
