---
name: Read Vault Secrets
description: "... it reads secrets from Vault?"
inputs:
  address:
    description: "the address of a deployed vault server"
    required: false
    default: https://vault.rancher.io
  secrets:
    description: "the secrets to fetch from the vault server"
    required: false
    default: secret/data/github-actions/test status
  cloudflare_access_client_id:
    description: "Cloudflare Access Client ID"
    required: true
  cloudflare_access_client_secret:
    description: "Cloudflare Access Client Secret"
outputs:
  secrets:
    description: "the secrets fetched from the vault server(json formatted)"
    value: ${{ steps.output.outputs.secrets }}
    
runs:
  using: composite
  steps:   
    - name: Read Secrets from Vault
      uses: hashicorp/vault-action@v3
      id: vault
      with:
        method: jwt
        url: ${{ inputs.address }}
        path: ${{ github.repository_owner }}
        role: ${{ github.event.repository.name }}
        secrets: ${{ inputs.secrets }}
        extraHeaders: |
          CF-Access-Client-Id: ${{ inputs.cloudflare_access_client_id }}
          CF-Access-Client-Secret: ${{ inputs.cloudflare_access_client_secret }}
        exportEnv: false 
        exportToken: false
        
    - name: Configure Outputs
      uses: actions/github-script@v7
      id: output
      with:
        script: |
          core.setOutput("secrets", ${{ toJSON(steps.vault.outputs) }});
          for (const [key, value] of Object.entries(${{ toJSON(steps.vault.outputs) }})) {
            core.setOutput(key, value);
          }
