---
name: Read Vault Secrets
description: "... it reads secrets from Vault?"
inputs:
  address:
    description: "the address of a deployed vault server"
    required: false
    default: https://vault.rancher.io
  secrets:
    description: "the secrets to fetch from the vault server"
    required: false
    default: secret/data/github-actions/test status
  cloudflare_access_client_id:
    description: "Cloudflare Access Client ID"
    required: true
  cloudflare_access_client_secret:
    description: "Cloudflare Access Client Secret"
outputs:
  vault-secrets:
    description: "JSON containing the vault secrets"
    value: ${{ steps.create-json.outputs.json }}
    
runs:
  using: composite
  steps:   
    - name: Read Secrets from Vault
      uses: hashicorp/vault-action@v3
      id: vault
      with:
        method: jwt
        url: ${{ inputs.address }}
        path: ${{ github.repository_owner }}
        role: ${{ github.event.repository.name }}
        secrets: ${{ inputs.secrets }}
        extraHeaders: |
          CF-Access-Client-Id: ${{ inputs.cloudflare_access_client_id }}
          CF-Access-Client-Secret: ${{ inputs.cloudflare_access_client_secret }}
        exportEnv: false 
        exportToken: false
    - name: Debug Available Outputs
      shell: bash
      run: |
        echo "Available vault step outputs:"
        echo '${{ toJSON(steps.vault.outputs) }}' | jq 'keys'
